#
# Build configuration for Circle CI
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"

general:
    artifacts:
        - /home/ubuntu/AndroidUITestEspresso/app/build/outputs/apk/

machine:
    environment:
        -sudo ANDROID_HOME: /usr/local/android-sdk-linux ./gradlew dependencies

dependencies:
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-19.1.0,android-19,extra-google-m2repository,extra-google-google_play_services,extra-android-support
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

test:
    override:
        - (./gradlew assemble):
            timeout: 360
